name: Terraform Destroy - FastAPI

on:
  # 수동 실행만 허용
  workflow_dispatch:

jobs:
  terraform-fastapi-dev-destroy:
    name: Terraform Destroy (FastAPI Dev)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Terraform Init
        working-directory: test/fastapi
        run: terraform init

      - name: Terraform Destroy
        working-directory: test/fastapi
        run: terraform destroy -auto-approve
