name: Terraform Apply - FastAPI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'test/fastapi/**'
      - 'test/modules/**'

jobs:
  terraform-fastapi-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Terraform Init
      working-directory: test/fastapi
      run: terraform init

    - name: Terraform Apply
      working-directory: test/fastapi
      run: terraform apply -auto-approve

    - name: Get EC2 Public IP from Terraform Output
      working-directory: test/fastapi
      run: |
        echo "DEV_FASTAPI_IP=$(terraform output -raw nebula_ai_eip)" >> $GITHUB_ENV

    - name: Update GitHub Organization Variables
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.request('PATCH /orgs/TU-NEBULA/actions/variables/DEV_FASTAPI_IP', {
            org: 'TU-NEBULA',
            name: 'DEV_FASTAPI_IP',
            value: process.env.DEV_FASTAPI_IP
          });
